### PR TITLE
Make keyboard start at A

### PR DESCRIPTION
**Pull request by rharkes**
Fixes Issue #38 by changing the layout of the keyboard to start at A instead of C. 
A better solution might be to re-create the `.mp3` files with the right pitch. However it was fun to figure out how to make the keyboard start at a different note.

Thanks for writing PianOli! The code is written in a clear way that made it possible for me to change something simple like this.

### CODE REVIEW

**Comment by nicolasbrailo** [comment]
Thanks for the PR @rharkes. Sorry it's taking me so long to accept it, I would like to give it a test run before I merge it, and I'm finding it hard to make time for it.

**Comment by nicolasbrailo** [comment]
Managed to build it and try it out. It works fine, though I found it a bit confusing  that instead of shifting the sounds it's the graphical keyboard that's shifted. @pserwylo what do you think, is it fine to shift the keys or would you find it better if we tried to shift the sounds instead?


Screenshot_20220328-200541_PianOli
.

**Comment by pserwylo** [comment]
Hmm, good question. Not a musician, so don'thl have a very useful opinion. However, I can see that shifting the keys has left a black space devoid of keys on the left of the screen (G perhaps? along with the missing A#?).

Maybe we take @rharkes other suggestion of regenerating notes, but I'd be happy to help script the processs so it is easier to update and regenerate the notes in the future if need be? Were theymadeusing relatively stock standard open source tools like audacity? Or something proprietary.

**Comment by nicolasbrailo** [comment]
The readme says I used https://onlinesequencer.net, but any midi generator + some ffmpeg should work.

**Comment by rharkes** [comment]
In your screenshot it looks like there is a black space the size of halve a note. How did that happen? For me it looked like this:
keyboard
The A# is there (black note to the right of the A, so in musical terms halve a tone above A) it has the configuration wheel in my screenshot. But there is no G# in the image. I used my paint-skills to add it in this image:
keyboard2

**Comment by rharkes** [comment]
Would it be possible to take the samples from here?
https://github.com/sfzinstruments/SplendidGrandPiano/
It is in the public domain.

**Comment by rharkes** [comment]
I made a sample-shortener that shortens the samples to one second, by taking the first second and doing a linear fade-out.
https://github.com/rharkes/sample_shortener

**Comment by pserwylo** [comment]
Haha, nice paint skills. My mistake, I was interpreting the black notification bar in your emulator/phone to be missing stuff from the screen:

image

However, I can see that the missing black key is also a bit off.

**Comment by rharkes** [comment]
I created a soundset that starts at C2 and goes up to B3, based on the sound files in [SplendidGrandPiano](https://github.com/sfzinstruments/SplendidGrandPiano/)

**Comment by nicolasbrailo** [comment]
Thanks for the contribution @rharkes! You added 2 different sets, right? Is there a reason we'd want both and the old one? I'm thinking we can keep just one out of the three (I haven't had time to try it out yet so I don't know if there is a different between the tree sets)

**Comment by rharkes** [comment]
Yes, I don't know which one you prefer, or maybe none of them. The choice is yours.

**Comment by nicolasbrailo** [comment]
I think if we have an improved soundset we should merge it :)
There are a couple of things I don't understand

* Are you suggesting we keep the current piano soundset, and add a new one (or two) on top? If I'm reading the PR correctly, that'll be the behaviour.
* I checked n01 for piano2 and piano3, and they seem to have different pitch. Is that because I'm not a musician, or do they start from a different note?
* piano2 start from n00, but piano3 (and the current soundset) start from n01. Is that on purpose? I believe n00 will be ignored.

**Comment by rharkes** [comment]
Sorry for the late reply.
I made a mistake with the naming of the files (0-23 vs 1-24) Oops. Just updated the names. That's also the reason for the different pitch. 
I would choose one piano soundset, that would make the most sense to me. But which one do you like best?

**Comment by nicolasbrailo** [comment]
Ahh good to know I can identify when two notes are different then! Can't
say I have a preference for one or another. I'll pick an arbitrary one and
merge it, unless you have a preference for one of them.

**Comment by nicolasbrailo** [comment]
Thanks for the patch!

**Pull request merged**
