### PR TITLE
Consistency checks for dynamic strings, before adding "Frère Jacques" song. 

### PR DESCRIPTION
**Pull request by juleskers**
Ever since @pserwylo added the song-player in #28, I've wanted to add Frère Jacques ("are you sleeping, brother John").
I am 99% sure it has translations for all European languages, as since it definitely has Spanish, English and Chinese, we reach probably 75% of all living humans on the planet.

However, adding songs requires updating quite a few hardcoded strings in multiple places. Since I dislike "you just have to know where" as an answer, especially for open source projects hoping for new contributors, I've added unit tests that check these implicit consistency rules. 

It's definitely not perfect, but I think it covers most cases:

### CODE REVIEW

**Review by pserwylo — COMMENTED** [review]
Thanks for the new song, great addition. I also agree with the unit test principle here, and have done similar things in the past. For example, my libgdx based games try to ensure that there is no flakey translations, and the F-Droid project extensively thrashes out the translations to check for syntactic errors that the compiler wont pick up.

However, all the reflection in here is a bit hairy. If you are interested, I can add a commit on top of this that uses robolectric to allow accessing the actual `Context` and `Resources` objects from our app, but on the local JVM without the need for a running Android device. In practice, this results in a test API that levereages the `Context.getString()` method.

Example of obtaining a reference to `Resources` from the "real" (via whatever magic robolectric does) `Context`: https://stackoverflow.com/a/58617596

**Comment by juleskers** [comment]
> all the reflection in here is a bit hairy.

Oh, I totally agree! This is the best I could come up with without additional dependencies, but it's definitely not up to my usual standards. To much "clever" and way too brittle. 

I am very hesitant to add dependencies for this, because everything I could think of (e.g. Class path scanning with [ClassGraph](https://github.com/classgraph/classgraph)) feels like _way_ overkill.  However, I may have to accept that Android Context is a complex beast, which requires big guns to deal with.  



 I'd be very happy with something more robust, but I am really running into my inexperience with the Android platform (PianOli is my first Android experience) . For example I've never heard of "robolectric" before. 
Their self-description on github sounds like it could be exactly what I was looking for (access context, but without emulator) , but I'm always a bit hesitant to believe the marketing blurbs. Are they really the "industry standard" like they claim? I lack the context to judge their plausibility.

One concern I have with robolectric: is it compatible with JUnit5? The examples I saw all work with JUnit4, and the plugin I added for 5 doesn't seem very "industry standard".

Feel free to add commits on top, I think your greater experience here could teach me a thing or two! 💙

**Comment by pserwylo** [comment]
For sure, it is a wild west out there. I believe robolectric is "industry standard" for lack of a better word. If you google "Android tests" you go to the official docs for running local tests on the JVM: https://developer.android.com/training/testing/local-tests#dependencies. Note how this has a comment mentioning "robolectric environment".

And yes, it is still JUnit4. Perhaps that is why the aforementioned docs page has a dependency for JUnit4. However, a Google earlier showed that this seems likely to change, and so if we really want to stick with JUnit5, then we need `junit-vintage-engine` which seems like it is from the official JUnit5 folk. This lets you use the `@RunsWith(RobolectricRunner.class)` style of running tests while still using JUnit4. Seemed to me that it still downloads all of junit4 when doing a gradle build, which is a bit of a mess.

For what it is worth, I agree that pushing `Context` outward is a great idea. But as you also mentioned, you eventually run out of things that can be tested with pure Java.

**Comment by juleskers** [comment]
So, some reading shows that robolectric has not been ported to junit5.  
- https://github.com/mannodermaus/android-junit5/issues/305
- https://github.com/robolectric/robolectric/issues/3477


Robolectric is currently hard-coupled to the way junit5 does classloading. This mechanism *could* be ported to a junit5 extension, but nobody has prioritised this work in the last 6 years. 
I get the impression this is unlikely to change as long as junit5 is not officially supported by android itself.

**Comment by juleskers** [comment]
Time for bed now (reaaaaally, 3:09 in the night), but I wanted to bang out the Theme-as-Enum idea.

(Bonus: coding with a sleeping baby on your lap grants the Wife some uninterrupted sleep)

**Pull request merged**
