### PR TITLE
ptbr translation

### PR DESCRIPTION
**Pull request by mezysinc**

### CODE REVIEW

**Comment by nicolasbrailo** [comment]
This is amazing, thanks for the PR!

**Comment by mezysinc** [comment]
There are some missing strings like:


1) First app splash screen

Screen is pinned
This keeps it in view until you unpin it.
Got it, no thanks 

2) Other OS tip

To unpin still screen, touch & hold Back & Overview buttons


Screenshot_20210829-193958_PianOli

**Comment by nicolasbrailo** [comment]
@mezysinc is it possible your phone is set up in English? Those are OS messages and come from Android, they are not defined by this app.

**Comment by mezysinc** [comment]
Yes I run few langs, but if you look at English strings here:
https://github.com/nicolasbrailo/PianOli/blob/master/app/src/main/res/values/strings.xml

there is nothing that looks like these below:

1) To unpin this screen, touch & hold Back & Overview buttons, **see ref.1 below**
&
2) Screen is pinned
This keeps it in view until you unpin it.
Got it, no thanks, **see ref.2 below**

Image **ref. 1**
Strings_PianOli_2

Image **ref. 2**
Strings_PianOli_1

**Comment by nicolasbrailo** [comment]
Yes, those are all Android screens; this app doesn't create a screen to ask the user to pin the app, it will ask Android "May I be pinned", then Android will ask the user with no further intervention of this app. That's why you won't find these strings in the app's resources, they can't be translated. If you change your phone's language to be in Portuguese, these messages should be translated appropriately.

**Comment by mezysinc** [comment]
I thought it was coming from your app, good to know

**Pull request merged**
