### PR TITLE
Brighten coloured keys when pressed, instead of darkening.

### PR DESCRIPTION
**Pull request by pserwylo**
Make a special case for green and yellow which need to be brightened more than others to visually appear distinct, due to their original brightness.

I'll comment back in 30mins or so to let you know how it goes with baby (currently has messy dinner hands).

### CODE REVIEW

**Comment by pserwylo** [comment]
Can confirm, it is a hit. Coloured keys are back in vouge with this 13 month old.

**Comment by pserwylo** [comment]
Fixes #24.

**Comment by nicolasbrailo** [comment]
@pserwylo could you also bump the version in build.gradle so it'll be picked up by fdroid? (eg: https://github.com/nicolasbrailo/PianOli/commit/fcbfc34536da7b3440d091aeacc88737a1ea0a09) Thanks for the PR!

**Comment by pserwylo** [comment]
Good call, happy to do this with future pull requests too.

@nicolasbrailo: Happy for me to add the following changelog in the `fastlane` metadata to also get picked up by F-Droid?

> Make keys more fun for little fingers to press (colored keys go brighter rather than darker when pressed).

**Comment by nicolasbrailo** [comment]
Yup, looks like the right thing to do! Thanks a lot for the changes

**Pull request merged**
